{% set name = "quantile-forest" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantile_forest-{{ version }}.tar.gz
  sha256: 1d0edf8b2f1c4b7d11c940cf1e5740a5381e1d250e5db0feea82d9282c52dab5

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=3.0a4
    - numpy >=2.0
    - scikit-learn >=1.5
    - scipy >=1.4
  run:
    - python
    - numpy >=1.23
    - scikit-learn >=1.5
    - scipy >=1.4

test:
  imports:
    - examples
    - quantile_forest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://zillow.github.io/quantile-forest
  summary: Quantile regression forests compatible with scikit-learn.
  dev_url: https://github.com/zillow/quantile-forest
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - reidjohnson
